default: &default
  url: 'http://localhost:3000'
  action_mailer:
    delivery_method: 'test'
  execution_logger:
    type: 'Void'
  custom_tasks:
  notifiers:
    mail:
      mail_from: 'Kuroko2 <no-reply@example.com>'
      mail_to: "kuroko@example.com"
    slack:
      webhook_url: 'https://localhost/test/slack'
    hipchat:
      api_token: 'token'
  api_basic_authentication_applications:
    test_client_name: 'secret_key'
  app_authentication:
    google_oauth2:
      client_id: '<%= ENV["GOOGLE_CLIENT_ID"] %>'
      client_secret: '<%= ENV["GOOGLE_CLIENT_SECRET"] %>'
      options:
        hd: '<%= ENV["GOOGLE_HOSTED_DOMAIN"] %>'
  extentions:
    controller:
development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
